import { type NextPage } from "next"
import Head from "next/head"
import { Note } from "../Note"
import { useNotes } from "../useNotes"
import { useEffect, useRef } from "react"
import autoAnimate from "@formkit/auto-animate"

const Home: NextPage = () => {
  const animateRef = useRef<HTMLDivElement>(null)
  const {
    notes,
    onCreateNoteClick,
    isCreateNew,
    onCloseCreateNoteClick,
    handleCreateNote,
    handleDeleteNote,
    handleEditNote,
  } = useNotes()

  useEffect(() => {
    animateRef.current && autoAnimate(animateRef.current)
  }, [animateRef])

  return (
    <>
      <Head>
        <title>16/27 - Notes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        data-theme="synthwave"
        className="flex min-h-screen flex-col gap-4 p-8 text-center"
      >
        <h1 className="m-6 text-4xl font-extrabold tracking-tight">
          16/27 - Notes
        </h1>
        <div>
          <button
            className="btn-primary btn-lg btn mb-8"
            onClick={onCreateNoteClick}
          >
            Create Note
          </button>
          <div ref={animateRef} className="flex flex-wrap justify-center gap-4">
            {isCreateNew && (
              <Note
                note={undefined}
                isCreate
                handleCreateNote={handleCreateNote}
                onCloseCreateNoteClick={onCloseCreateNoteClick}
              />
            )}

            {notes?.map((note) => (
              <Note
                key={note.id}
                note={note}
                handleDeleteNote={handleDeleteNote}
                handleEditNote={handleEditNote}
              />
            ))}
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
