import { type NextPage } from "next"
import Head from "next/head"
import { atom, useAtom } from "jotai"

const textAtom = atom("16/27 - Notes")

const Home: NextPage = () => {
  const [text] = useAtom(textAtom)

  return (
    <>
      <Head>
        <title>{text}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        data-theme="synthwave"
        className="flex min-h-screen flex-col gap-4 text-center"
      >
        <h1 className="m-6 text-4xl font-extrabold tracking-tight">{text}</h1>
      </main>
    </>
  )
}

export default Home
